// Autogenerated from Pigeon (v18.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Generated class from Pigeon that represents data sent in messages.
struct InitializeParam {
  var dummy: String

  static func fromList(_ list: [Any?]) -> InitializeParam? {
    let dummy = list[0] as! String

    return InitializeParam(
      dummy: dummy
    )
  }
  func toList() -> [Any?] {
    return [
      dummy
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct InitializeResult {
  var dummy: String

  static func fromList(_ list: [Any?]) -> InitializeResult? {
    let dummy = list[0] as! String

    return InitializeResult(
      dummy: dummy
    )
  }
  func toList() -> [Any?] {
    return [
      dummy
    ]
  }
}
private class IMAPlayerApiCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 128:
      return InitializeParam.fromList(self.readValue() as! [Any?])
    case 129:
      return InitializeResult.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class IMAPlayerApiCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? InitializeParam {
      super.writeByte(128)
      super.writeValue(value.toList())
    } else if let value = value as? InitializeResult {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class IMAPlayerApiCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return IMAPlayerApiCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return IMAPlayerApiCodecWriter(data: data)
  }
}

class IMAPlayerApiCodec: FlutterStandardMessageCodec {
  static let shared = IMAPlayerApiCodec(readerWriter: IMAPlayerApiCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol IMAPlayerApi {
  func initialize(param: InitializeParam) throws -> InitializeResult
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class IMAPlayerApiSetup {
  /// The codec used by IMAPlayerApi.
  static var codec: FlutterStandardMessageCodec { IMAPlayerApiCodec.shared }
  /// Sets up an instance of `IMAPlayerApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: IMAPlayerApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let initializeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_ima_sdk_sample.IMAPlayerApi.initialize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let paramArg = args[0] as! InitializeParam
        do {
          let result = try api.initialize(param: paramArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      initializeChannel.setMessageHandler(nil)
    }
  }
}
