name: flutter_ima_sdk_sample
description: "A new Flutter plugin project."
version: 0.0.1
homepage: "https://github.com/noboru-i/flutter_ima_sdk_sample"

environment:
  sdk: ">=3.3.3 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  pigeon: ^18.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_ima_sdk_sample
        pluginClass: FlutterImaSdkSamplePlugin
      ios:
        pluginClass: FlutterImaSdkSamplePlugin
